[pytest]
addopts = -v -s --headed --browser chromium

testpaths = 
    Test_Case/test_api
    Test_Case/test_ui

 markers =
    ui: Frontend web automation tests with Playwright
    api: Backend API integration tests
    smoke: Critical sanity verification flows
    regression: Complete end-to-end framework test suite

#run exampel: pytest -m regression
#To run only login using text filtering: pytest -m ui -k login