[pytest]
addopts = -v -s --headed --browser chromium

testpaths = 
    Test_Case/test_api
    Test_Case/test_ui

  markers =
    api: Marks tests as backend API automation tests
    ui: Marks tests as frontend UI web automation tests
    smoke: Marks critical tests for quick sanity checks (Sanity suite)
    regression: Marks all tests for complete application testing (Full suite)



#run exampel: pytest -m regression